class BuiltinCommands(object):
  QUIT = 'quit'
  CANCEL = 'cancel'

  PREV_LINE = 'prev_line'
  NEXT_LINE = 'next_line'
  PREV_CHAR = 'prev_char'
  NEXT_CHAR = 'next_char'
  PREV_WORD = 'prev_word'
  NEXT_WORD = 'next_word'
  PREV_PAGE = 'prev_page'
  NEXT_PAGE = 'next_page'
  START_OF_LINE = 'start_of_line'
  END_OF_LINE = 'end_of_line'
  KILL_TO_END_OF_LINE = 'kill_to_end_of_line'
  KILL_TO_START_OF_LINE = 'kill_to_start_of_line'
  PUSH_MARK = 'push_mark'
  POP_MARK = 'pop_mark'
  COPY = 'copy'
  PASTE = 'paste'
  COPY_PASTE_HISTORY = 'copy_paste_history'
