name: Create Assets

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check_compilation:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        cc: [gcc, clang]
        nvim_tag: [stable]
        exclude:
          - os: windows-2022
            cc: clang
            nvim_tag: stable

        include:
          - os: windows-2022
            cc: cl
            nvim_tag: stable

    name: Parser compilation
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      NVIM: ${{ matrix.os == 'windows-2022' && 'nvim-win64\\bin\\nvim.exe' || 'nvim' }}
      ALLOWED_INSTALLATION_FAILURES: ${{ matrix.os == 'windows-2022' && 'rnoweb' }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: nvim-treesitter/nvim-treesitter
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-node@v3

      - name: Install tree-sitter CLI
        run: npm i -g tree-sitter-cli

      - name: Install and prepare Neovim
        env:
          NVIM_TAG: ${{ matrix.nvim_tag }}
        run: |
          bash ./scripts/ci-install-${{ matrix.os }}.sh

      - name: Compile parsers
        run: $NVIM --headless -c "lua require'nvim-treesitter.install'.prefer_git=false" -c "TSInstallSync all" -c "q"

      - name: Post compile Windows
        if: matrix.os == 'windows-2022'
        run: cp -r ~/AppData/Local/nvim-data/site/pack/packer/start/nvim-treesitter/parser/* parser

